### ISSUE TITLE
Verus coin update

### ISSUE THREAD

**Issue by xginxKH** [pangz-lab/verus_miner-release#1]
hi thanks for your great work we all wait for app update regarding the Verus PBaaS Activation

**Comment by pangz-lab** [comment]
Hello,

I'm working to add the new version with PBaas and merge mining support.

I hope to release it as soon as possible. Please join the discord group to get the latest update.

Cheers 🥂

**Comment by Amarullohzikri27105** [comment]
Hello, may I know where did you get the ccminer file in the assets file, please

**Comment by pangz-lab** [comment]
@Amarullohzikri27105 it's monkins1010 version. Please join our official discord group to know more.
