### ISSUE TITLE
app not installed

### ISSUE THREAD

**Issue by qaz7371** [pangz-lab/verus_miner-release#10]
after transferring the file onto my android phone and trying to install it it just says app not installed.
the phone is a samsung galaxy a10e

**Comment by pangz-lab** [comment]
More details would be good.
Most likely your phone OS is old or CPU architecture is 32 bit.

**Comment by qaz7371** [comment]
> Most likely your phone OS is old or CPU architecture is 32 bit.

it has a 64 bit cpu and its only a few years old(2019) so id assume it modern enough

**Comment by pangz-lab** [comment]
Some latest released phones have 32 bit mode enabled only so mining it is not possible. You can flash a 64bit rom if available. What's your phone model?

**Comment by qaz7371** [comment]
> Some latest released phones have 32 bit mode enabled only so mining it is not possible. You can flash a 64bit rom if available. What's your phone model?

its a samsung galaxy a10e if that answers your question

**Comment by pangz-lab** [comment]
You have 64bit cpu though it can also be 32bit enabled only. You can use VerusBox and see the phone info. You'll know if it's mineable.

**Comment by qaz7371** [comment]
> You have 64bit cpu though it can also be 32bit enabled only. You can use VerusBox and see the phone info. You'll know if it's mineable.

oh. it says not mineable, is there any way to work around that or is it just thats that cant do it on that phone?

**Comment by pangz-lab** [comment]
You can flash a custom 64bit rom. It's not a simple procedure but doable. You can find references online. Another way is to find 2nd hand phones. That's the fastest.

**Comment by qaz7371** [comment]
> You can flash a custom 64bit rom. It's not a simple procedure but doable. You can find references online. Another way is to find 2nd hand phones. That's the fastest.

okay, thanks. since i got alot of spare time ig ill flash a 64 bit rom onto it.

**Comment by pangz-lab** [comment]
I'll close this issue now. Please join the official VerusMiner/VerusBox discord group if you can.
