### ISSUE TITLE
Device says APK not supported generic or ca35 installer

### ISSUE THREAD

**Issue by mchipser** [pangz-lab/verus_miner-release#15]
Attempting to install on a ONN Media streamer (2023). Its specs show it is powered by a "CPU: Quad-core Cortex-A35, GPU: Mali-G31 MP2". Is it possible to add support for this model, it is a super cheap ($20) device that could be a decent miner instead of phones. 

https://www.walmart.com/ip/onn-Google-TV-4K-Streaming-Box-New-2023-4K-UHD-resolution/2835618394?clickid=yQfV1oV7dxyPROK1A5QHc2kYUkHySuSPIzKJQA0&irgwc=1&sourceid=imp_yQfV1oV7dxyPROK1A5QHc2kYUkHySuSPIzKJQA0&veh=aff&wmlspartner=imp_3690421&affiliates_ad_id=565706&campaign_id=9383&sharedid=

**Comment by PSLLSP** [comment]
Try to install and run [AIDA64](https://www.aida64.com/aida64-android), check information about your Android. I guess that your device has 64-bit CPU but runs only 32-bit Android, like most of these cheap boxes. 32-bit Android is the showstopper for your device... Other issue could be that device doesn't have enough RAM. Some of those devices have 4 GB of RAM but configured in such way that it can be used only as a cache and only about 1 GB of RAM can be used directly be applications; not great configuration... Check this [video on YouTube](https://www.youtube.com/watch?v=1vpepaQ-VQQ), it is about cheap TV boxes.

**Comment by mchipser** [comment]
That does look like what is happening.. thanks!
