### ISSUE TITLE
Autostart to mining

### ISSUE THREAD

**Issue by Dacode07** [pangz-lab/verus_miner-release#16]
Hi Pangz, thank you for your service, I love to use it on all my phones but I would like to ask you to add a setting to the app to start the mining process automatically, is it possible to add an option to start automining automatically when the app starts? The reason I want this is that sometimes my phones restart themselves due to overheating and I want to automate this process by automatically starting the mining application you have prepared at the start of the phone

**Comment by pangz-lab** [comment]
Hello @Dacode07 . You're welcome.
You might wanna see this workaround. Basically the app have some limitations but what you want to do is achievable.
Please see the link.
https://github.com/pangz-lab/verus_box-release/blob/master/HELP.md#setup-verusminer-to-start-mining-on-boot

For overheating problem, you might wanna enable the temperature control. It will stop the mining at a certain temperature and will restart automatically after the cooldown time you set.

Cheers
