### ISSUE TITLE
Huawei Y6 2019

### ISSUE THREAD

**Issue by Meps164a** [pangz-lab/verus_miner-release#17]
Hello!

I'm trying to install this apk on an old android 9 phone that i don't use anymore, but i can't get it to work.

I go to files and click on app.apk (latest version) it ask me if i want to install and i click install. It loads the installation bar for 5 seconds and then says "The app was not installed". 

I have allowed to install apps from external sources and i've done so with some other apk files which worked just fine. 

It has a Quad-core 2.0 GHz Cortex-A53 CPU which is 64-bit, maybe it's the 2 GB of ram that does not allow me to? Or is the phone simply just not supported? 

Thanks in advance!

**Comment by pangz-lab** [comment]
I guess it's the 2G RAM. CA53 have 32 bit variant and usually, phones with 2Gig of Ram only enables the 32bit instructions. That's most likely the cause.

You can check this issue
https://github.com/pangz-lab/verus_miner-release/issues/15#issuecomment-1995479707

**Comment by Meps164a** [comment]
Aww man, but thank you anyway for the answer! 

Edit: just checked with the AIDA64 app, and you're right, it says "64-bit ARMv8-A (32-bit mode)"
