### ISSUE TITLE
Unable to set nicehash wallet address

### ISSUE THREAD

**Issue by swagkiller69** [pangz-lab/verus_miner-release#2]
Hiya. I noticed there's an option under pools for the nicehash VerusHash stratum, but attempting to input my btc wallet address gives an error that the address is invalid, making it impossible to put the phones onto nicehash!

Thanks in advance

**Comment by pangz-lab** [comment]
Hello,

You can use a non-verus wallet address using the custom parameters field. Not from the wallet address field. you need to set "-u non-verus-wallet" without double quotes(").

Please join our discord group for further support.

🥂

**Comment by pangz-lab** [comment]
The needed feature is existing already.
