### ISSUE TITLE
Support for other coin wallets (for auto-exchange pools)

### ISSUE THREAD

**Issue by ilanodem** [pangz-lab/verus_miner-release#20]
I try to add a config to mine with zergpool and get paid in monero. When I input my monero wallet address it says format is invalid. That's how it works in the pool. Please make the app accept other wallets

**Comment by pangz-lab** [comment]
Please check this comment 
https://github.com/pangz-lab/verus_miner-release/issues/11#issuecomment-1849516541

**Comment by pangz-lab** [comment]
Will be closing this issue now. If you need further support, you can join our official discord group. https://discord.com/invite/74AsRqvA
