### ISSUE TITLE
Implicit Wakelock in hashing screen?

### ISSUE THREAD

**Issue by supasnipa360** [pangz-lab/verus_miner-release#3]
It appears the hashing screen stays awake with or without dev options "Stay awake" or some other wakelock being active. Would be helpful as a checkbox option in overall or mining profile settings.

**Comment by pangz-lab** [comment]
The wakelock is the setting you enabled on the first run when you're being asked to allow the miner to run in the background. 

Still you can if you need the screen off. Some phones allow the miner to run in the background, some don't. You need to check if it works for you.

**Comment by supasnipa360** [comment]
Thanks for the response. So if one was to seek a 3rd party wakelock. It won't necessarily fix that issue seen with some phones will it?

**Comment by pangz-lab** [comment]
> 

Yes. Even with 3P wakelock app, I expect it still won't work as the app is using the same native commands that enables it. However I encourage you to try it and see if works. I could be wrong.

**Comment by supasnipa360** [comment]
I figured out the issue. One is on my side (Poor wifi coverage). The other appears to be the thread hangs in the miner under certain scenarios where theres network issues, possibly packet losses? Im not going to open another issue. However, might be worth seeing if theres some optimization of handling pool / network connection that can be done.

**Comment by pangz-lab** [comment]
Could you share why you think there's a thread hang or packet loss when connecting to your network? Do you use packet sniffer like wireshark or something?
