### ISSUE TITLE
Feature Request Autostart Mining

### ISSUE THREAD

**Issue by Luxi84** [pangz-lab/verus_miner-release#31]
Hallo it would be Nice, when there would be a setting like (autostart Mining/restart Mining) so that it can be activatet, that when the App starts it starts Mining automaticly and restarts it if it is off, or did I just not see this Option?

**Comment by pangz-lab** [comment]
There's a cooldown feature built into the app that you can try. Also you can auto start mining if your phones turn off.

You can check this.

https://github.com/pangz-lab/verus_miner-release/issues/29#issuecomment-2443964634
