### ISSUE TITLE
USERNAME is limited to VRSC address

### ISSUE THREAD

**Issue by PSLLSP** [pangz-lab/verus_miner-release#5]
Verus miner 3.4.1

Form in the miner configuration validates USERNAME (that is called WALLET ADDRESS), it has to be VRSC address. That is true in most cases but parameter `-u` to the miner means **username**, not address... Please, change this check to just warning, I would like to enter username that is not valid VRSC address... With current setup I cannot enter username as it is not valid address and I cannot save the configuration, so I am limited to pools that has VRSC address as username.

One example, ZERG pool allows users to mine one coin but get paid in other coin and that other coin address is username. So, I want to mine VRSC but get paid in BTC, so my username is BTC address and password field describes what to mine and what to earn... I cannot use such setup with current Verus miner for Android, I am limited to VRSC coin... :-(

**Comment by pangz-lab** [comment]
Just leave the wallet address as it is then configure using custom parameters.

Basically each flag with value should be separated

Like 
-u nonveruswallet;-p c=BBC;

**Comment by PSLLSP** [comment]
Similar issue with MINER NAME (or WORKER NAME) field. It is mandatory and it is added to **username**. ZERG pool doesn't use this schema, WORKER name is passed in password field. I cannot save configuration when WORKER NAME is empty... :-(

**Comment by pangz-lab** [comment]
> Similar issue with MINER NAME (or WORKER NAME) field. It is mandatory and it is added to **username**. ZERG pool doesn't use this schema, WORKER name is passed in password field. I cannot save configuration when WORKER NAME is empty... :-(

Just leave the username as it is.
You can share here the format of configuration you want to use. It's already supported. You just need to ask.

**Comment by PSLLSP** [comment]
PORT in Custom POOL configuration is limited to 4 digits, like TCP port 9999 is the highest port that can be used. This is wrong assumption, TCP port can be in range 1-65535, it is 16-bit unsigned integer..

PASSWORD filed is not in the form...

I understand I can overwrite all hose fields with custom parameter but it is confusing. And running miner shows information entered to the form filelds, not real configuration that it use!!! :-( Really confusing...

**Comment by pangz-lab** [comment]
> PORT in Custom POOL configuration is limited to 4 digits, like TCP port 9999 is the highest port that can be used. This is wrong assumption, TCP port can be in range 1-65535, it is 16-bit unsigned integer..
> 
> PASSWORD filed is not in the form...
> 
> I understand I can overwrite all hose fields with custom parameter but it is confusing. And running miner shows information entered to the form filelds, not real configuration that it use!!! :-( Really confusing...

Well, since you know so much, probably the best way for  now is to create your own miner.

I will close this issue now. This is not a place to whine or share your ideals and aspirations.

**Comment by PSLLSP** [comment]
Try this configuration:

-o stratum+tcp://eu-01.miningrigrentals.com:3333 -u droidMiner.217232 -p TESTBOX1

When it fails, then Verus miner doesn't support [**client.reconnect**](https://en.bitcoin.it/wiki/Stratum_mining_protocol#client.reconnect) method

This is just a workaround when miner doesn't support client.reconnect, TCP port 50361 was dynamically allocated and will be closed in a week:

-o stratum+tcp://eu-01.miningrigrentals.com:50361 -u droidMiner.217232 -p TESTBOX2
