### ISSUE TITLE
I can't download the app

### ISSUE THREAD

**Issue by Zarake0-0** [pangz-lab/verus_miner-release#6]
Hello, I can't download the application writes "the application is not installed" downloaded the latest version to the Redmi S2 phone
![Screenshot_2023-10-13-15-34-58-318_com google android packageinstaller](https://github.com/pangz-lab/verus_miner-release/assets/113696077/eb0614f8-3533-4dd6-8737-47fb940177f9)

**Comment by pangz-lab** [comment]
Hello. Please check the phone CPU and OS. Both should be 64bit.If not, it cannot be installed or mine. please share a link to your phone. Let's check the architecture.

It's also possible that if you have an existing VerusMiner installed, you should uninstall it first. This happens to some phones sometimes.

**Comment by Zarake0-0** [comment]
https://www.devicespecifications.com/en/model/db9a4a24 this is a link to the phone. I checked the 64-bit processor, I have never installed the application before, so it is not on the phone

**Comment by pangz-lab** [comment]
Got it. That model should be OK.
Could you try to update your android version?

**Comment by Zarake0-0** [comment]
Я попробую обновить андроид

**Comment by Zarake0-0** [comment]
![Screenshot_2023-10-15-14-08-39-010_com pangzlab verus_miner](https://github.com/pangz-lab/verus_miner-release/assets/113696077/fb8d6139-e586-4de7-b89e-0a987bbc2c7b)
@pangz-lab Maybe it's because of the lack of Root rights?

**Comment by pangz-lab** [comment]
That explains it. Either your CPU or OS is not 64 bit. Most likely you have a 32bit mode in a 64bit CPU. Please check using cpu-z or other apps that checks the CPU and OS.

**Comment by Zarake0-0** [comment]
my processor is 32 bit. is there an application for 32 bit?

**Comment by pangz-lab** [comment]
Unfortunately NO. Actually it's not the app but the algorithm for mining. 32bit CPUs cannot simply be used for mining Verus.
