### ISSUE TITLE
could not install verusminer

### ISSUE THREAD

**Issue by rblana** [pangz-lab/verus_miner-release#7]
Hello I tries installing verusminer on a huawei Y6s and I got this error while trying to install with adb (It fails from the Android GUI).
`adb: failed to install app.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
`

The CPU is a octacore(armv8l):  Mediatek MT6765 Helio P35 (12nm) https://valid.x86.fr/a/v593e1

Is the SOC compatible? 

I found an answer that a build param is needed: 
https://stackoverflow.com/questions/36414219/install-failed-no-matching-abis-failed-to-extract-native-libraries-res-113

**Comment by pangz-lab** [comment]
Hello. Unfortunately armv8l is 32bit. The miner requires a 64bit OS and CPU.
