### ISSUE TITLE
Self hosted monitor

### ISSUE THREAD

**Issue by authrequest** [pangz-lab/verus_miner-release#8]
Is there a way to create our monitor? Need to know what protocol it's using so I can connect all my monitors locally to a custom coded UI. I'd rather ask here because i don't want to have to reverse the Flutter app.

**Comment by pangz-lab** [comment]
👋 Hello.
It's fine. Feel free to reverse engineer it.
For now there is no endpoint available for your needs as far as I understand your request.

If you want to monitor it online, you can access the online monitoring from here 

https://verusmonitor.is-now.live/

If there's really a need for external integration, we can talk about it and I can work on a design.

**Comment by authrequest** [comment]
Why is this information sent to your website? Is this data really needed??
![VersusMiner](https://github.com/pangz-lab/verus_miner-release/assets/42212841/2cade21e-ec54-46f2-928e-5091bd584b82)

**Comment by pangz-lab** [comment]
Hello,
It will be part of another feature for future release. For now it's used for support and maintenance.

**Comment by pangz-lab** [comment]
If you have other questions or concerns, best join the official discord group for VerusMiner.

See the link
https://discord.com/invite/9ggcH4ny
