### ISSUE TITLE
Does Not Mine in Background

### ISSUE THREAD

**Issue by vaishakhpj** [pangz-lab/verus_miner-release#9]
The Miner does not mine in background, my phone is POCO M4 pro 5G using Android 13. Whenever i navigate to other app the miner stops mining and have to restart again. please fix this.

**Comment by pangz-lab** [comment]
It's not the miner app. It's your phone that restricts the miner to run in the background. Try to change the settings. Usually, when you mine, you just let the miner app open. Running it with other resource intensive apps and constantly changing it will very likely get killed by the OS.

**Comment by pangz-lab** [comment]
> Please use foreground service instead of background service like used in a music player app with start stop panel notification. 
> Example : https://www.geeksforgeeks.org/foreground-service-in-android/

That's a different thing. Background service is enabled by default in the miner.

**Comment by vaishakhpj** [comment]
I you use foreground service then screen can be turned off while mining also the Android OS will not kill the app. Your App will become more popular because anybody can allocate 50 percent of CPU even with daily usage and mine coin. So everybody can use your app in their daily phones which are more powerful ones instead of dedicated phone requirement for mining.

**Comment by vaishakhpj** [comment]
Thank You for implementing. kudos for your work.

**Comment by pangz-lab** [comment]
@vaishakhpj - this is added in v5.0.0. 
Please check.

Cheers

**Comment by vaishakhpj** [comment]
Great Job.

**Comment by pangz-lab** [comment]
Thank you for pointing that out.
I really appreciate you raising this issue.
